services:
 app:
  container_name: auth-service
  build:
    context: .
    dockerfile: Dockerfile
  image: auth-service
  ports:
    - "8000:8000"
  env_file: .env
  working_dir: /app
  command: ./auth-service